all:
  hosts:
      10.1.166.102:
        ansible_user: goupilles
        ansible_password: "{{ vault_mdp_login_windows }}"
        ansible_connection: winrm  
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      10.1.166.105:
        ansible_user: goupilles
        ansible_password: "{{ vault_mdp_login_windows }}"
        ansible_connection: winrm  
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
