version: "3"

services:
  redis-sg:
    image: bitnami/redis-cluster
    container_name: redis-sg
    volumes:
      -  redis-cluster_data:/bitnami/redis/data
    restart: unless-stopped
    env_file:
     - .env
    extra_hosts:
      - "redis-fao:10.2.0.147"
      - "redis-jt:10.2.0.144"
      - "redis-lp:10.2.0.43"
      - "redis-sg docker-3:10.2.0.139"
      - "redis-sr:10.2.0.151"
      - "redis-tb:10.2.0.165"
      - "redis-vs:10.2.0.141"
    network_mode: "host" 

volumes:
  redis-cluster_data:
