version: "3"

services:
  droner-runner:
    restart: unless-stopped
    image:  drone/drone-runner-docker:1
    container_name: runner
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: bridge-user


