version: "3"

services:
  droner-server:
    restart: unless-stopped
    image: drone/drone:2
    container_name: drone
    ports:
      - 8100:80 
    volumes:
      - serverdata:/data
    env_file:
      - .env

networks:
  default:
    name: bridge-user

volumes:
  serverdata: