version: "3"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
      - ./sample.ini:/conf/sample.ini
    ports:
      - "3001:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://10.2.0.139:3001/

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    volumes:
      - loki:/loki
      - ./loki-config.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  loki:
  grafana:

networks:
  default:
    name: bridge-user
