version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  php:
    container_name: php
    image: php:8-fpm-alpine
    volumes:
     - ./html:/usr/share/nginx/html/

networks:
  default:
    name: bridge-user
