version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1-alpine
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
#    ports:
#      - 8087:3001
    restart: unless-stopped

networks:
  default:
    name: bridge-user

volumes:
  uptime-kuma:
