- name: création de runnertemp
  ansible.builtin.file:
    state: directory
    path: /root/runnertemp/

- name: Copy du jinja
  ansible.builtin.template:
    src: .env.j2  
    dest: /root/runnertemp/.env

- name: Copy compose
  ansible.builtin.copy:
    src: docker-compose.yml 
    dest: /root/runnertemp

- name: install des runners
  community.docker.docker_compose:
    project_src: /root/runnertemp
    state: present
    recreate: always