version: "3"

services:
  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/log/glances.log:/var/log/glances.log
      - /var/log/journal:/var/log/journal
    command: -config.file=/etc/promtail/config.yml

networks:
  default:
    name: bridge-user