server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.2.0.139:3100/loki/api/v1/push

scrape_configs:
  - job_name: glances
    static_configs:
    - targets:
      - localhost
      labels:
        job: glances
        __path__: /var/log/glances.log

  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'nodename'
