version: "3"

services:
  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8090:80"
    volumes:
      - pgvol-sql:/var/lib/pgadmin
    env_file:
      - .env

networks:
  default:
    name: bridge-user

volumes:
  pgvol-sql: